### ISSUE TITLE
Dust Generator isnt "supported" in 1.16.3 due to Ex Nihilo getting a new name

### ISSUE THREAD

**Issue by Algester** [rafacost/usrg#1]
Dust generator is not available by virtue of Ex Nihilio Creatio is now Ex Nihilo Sequentia (thing is maybe different modders?), also can I possibly have a request for Diorite and Granite Generators as well?

I mean since they are "alternatives" of stone maybe change the central element to Diorite and Granite?

**Comment by rafacost** [comment]
Fixed on 1.16.4
