### ISSUE TITLE
Additional Features

### ISSUE THREAD

**Issue by Bletch1971** [rafacost/usrg#6]
I would like to know if you would be interested in the following changes:

1. Implement the blocks_per_tick config setting into all the standard generators, like it is in the ore generator.

2. Have a config setting to switch the Clay, Glowstone, Quartz, Redstone and Snow Generators between generating block and dust items. 
e.g. config setting would be - Generate Dust (Generate dust instead of blocks for the Clay, Glowstone, Quartz, Redstone and Snow Generators).

Happy to start working on them if you agree

**Comment by rafacost** [comment]
Nice! I think that would be nice additions to the mod! I saw that you already commited. I will check the code and merge. Lets talk about any other ideas you have.

**Comment by Bletch1971** [comment]
Thanks for implementing all the changes I did.
I have only just found this mod recently and I love it, it is great for skyblock packs.

Just wanted to add back the Dust Generator, and new gens for the crushed blocks used in sieving in Ex Nihilo. While I do not mind sieving, I hate hammering the blocks into other variants.

I thought your ore generator was a great idea, and I liked the idea of extending it so that mod packs could customise the output with their own probabilities.

I just read through the comment section of your mod, and found similar requests :)

One more thing I was thinking about - Dye Generator. 
* Similar to the ore generator, but creates one dye per generation cycle. 
* The dyes can be hardcoded to include all vanilla dyes, they do not need a config option like the ore generator.
* Just define all the vanilla dyes and all have the same probability of 1?
* The recipe should allow any vanilla dye, and maybe diamond shovels/hoes, with two buckets of water?

I was also thinking of updating the generator texture files, nothing radical, just making them consistent and cleaning them up a little.
Not sure if you are ok with that or not.

If you would prefer to reach out to me via email - bletch1971@hotmail.com

Thanks again for this great mod.

**Comment by Bletch1971** [comment]
### New Textures

Flat with diamond image in appropriate colors
![_new2](https://user-images.githubusercontent.com/4722854/104551962-937bca00-5683-11eb-902a-8cfad6aee43b.png)

3d(ish) with diamond image in appropriate colors
![_new3](https://user-images.githubusercontent.com/4722854/104552044-befeb480-5683-11eb-8294-b902c3901376.png)

What do you think?

**Comment by Bletch1971** [comment]
I have created two PRs one for each change.

If you do not like either of them, then just close the PRs. I am happy to work with you if you want to re texture them, but I am not very good at graphics, these are very basic.

**Comment by rafacost** [comment]
Thank you Bletch1971 for all the hard work.
So, it's been a long time that I wanted to change the model for the generator. But never got the time. After seen you get involved with the project, it gave me a new motivation to sit my ass down and get to work.
So I had this design in my mind. With to containers side by side (lava and water) and the resource that been created rotating at the middle. So far I manage to create a static version of the model. (I need to figure out how to use moving textures (for the liquid) and spin the block inside, also add transparency to the water, and setlightlevel to lava) . 
Take a look and tell me what do you think.
![Screenshot 2021-01-16 092556](https://user-images.githubusercontent.com/7635588/104811888-56c3e600-57dd-11eb-863c-82d27ff17035.png)

Sorry to not use your textures, loved them by the way.

About the Dye Generator, it's a really good idea, you can go for it if you like.
I was also thinking, I hate mob farms in skyblocks. Maybe we could add Mob Drops Gens? (One for each type, or one like the OreGen?) What do you think? (Will the mod be too OP?)

Once again, thank you for your hard work! Loved your contributions!

**Comment by Bletch1971** [comment]
The new model looks good, I did not stray far from your original design, just cleaned them up a little, but your idea is a better one. Just close the two pull requests I created with the new textures.

I will be submitting one more pull request soon, nothing major just some little extras.

As for the dye generator, I will look to add it, along with an option to enable/disable it.
I do like the idea of a mob drop generator, again it might be worth having a config option to enable/disable it, so that it can be turned off if they think it OP.

I have loved contributing to the mod, the last mod I did was for 1.12, and things have changed so much, I want something to also learn from with the newer versions.

**Comment by Bletch1971** [comment]
I have some questions for you

1. rather than all the block models use water and lava in them, would it be possible to change them so they show what the recipe uses?
For example: Snow Generator only uses water, so would show water on both sides.
Netherrack generator only uses lava, so would show lava on both sides.

2. rather than all recipes using the same axe, shovel, pickaxe across the top and bottom, can we change the recipe for all of them to include Stone in all four corners?
For example: Cobble Generator
sps
lcw
sps

s = minecraft:stone
p = <pickaxe, shovel, axe etc>
l = lava
w = water
c = specific block/item

**Comment by rafacost** [comment]
Agree with both! Let's do it!

**Comment by Bletch1971** [comment]
I was playing around with the block models last night and came up with a mock solution that shows flowing water/lava. It is pretty rough and I still need to work a few things out, but are you interested in that?

**Comment by rafacost** [comment]
Sure! 
During this week I will look into make that resource block spining. I think it will be a nice feature to have.

**Comment by rafacost** [comment]
Hey Bletch1971, I've updated the mod to 1.16.5. I've tested locally, but not with Ex:Nihilo. Hope I didnt break anything. :)

**Comment by Bletch1971** [comment]
Hey, I have submitted two new PR, one for the 1.16.4 branch and one for the 1.16.5 branch.
They contain exactly the same changes, but I wanted one last update to the 1.16.4 branch as the mod pack I am currently playing is 1.16.4.

I hope you like everything I have done, it took me for bloody ever to work out the new Models.

**Comment by rafacost** [comment]
Hi!!!! Amazing work on the models!!! They look fantastic!!! I look forward to play your modpack! I've already pushed the 1.16.4 file to curse. I'm compiling 1.16.5 right now. Once again, thanks a lot mate!

**Comment by Bletch1971** [comment]
I have just implemented the last set of things I wanted to implement 

1. generator block rotation. When you place the generator now it will place facing away from you, so now you can change the way the generator faces.
2. I have pushed some of the tile class code to the base class.
3. I have created a base random tile class for the random generators.

I have done the changes for 1.16.3, 1.16.4 and master branches.

**Comment by rafacost** [comment]
@Bletch1971 Thank you for all your hard work!

**Comment by Bletch1971** [comment]
@rafacost you are welcome, this is a great mod and happy to have contributed to it.
